# Fly.io configuration для WebSocket сервера
app = "copella-websocket"
primary_region = "ams" # Amsterdam - ближе к Европе

[build]
  [build.args]
    NODE_VERSION = "20"

[env]
  NODE_ENV = "production"
  WS_PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false  # Важно! Не останавливать машины
  auto_start_machines = true
  min_machines_running = 1    # Всегда 1 машина запущена

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

