services:
  # WebSocket Server
  - type: web
    name: copella-websocket
    runtime: node
    plan: free
    buildCommand: npm install && npm run db:generate
    startCommand: npm run start:ws
    envVars:
      - key: WS_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Будет задано вручную
      - key: PUBLIC_SUPABASE_URL
        sync: false  # Будет задано вручную
      - key: PUBLIC_SUPABASE_ANON_KEY
        sync: false  # Будет задано вручную
      - key: PUBLIC_FRONTEND_URL
        sync: false  # URL вашего фронтенда на Vercel
    healthCheckPath: /health

